version: "3"

services:
  garage:
    image: dxflrs/garage:v2.2.0
    container_name: tunnelvision_garage
    env_file: "compose.env"
    ports:
      - "3900:3900"
      - "3901:3901"
    volumes:
      - garage-data:/data
      - garage-meta:/meta
      - ./garage.toml:/etc/garage.toml
    restart: unless-stopped

  db:
    image: docker.io/postgres:17
    container_name: tunnelvision_db
    restart: unless-stopped
    shm_size: 128mb
    env_file: "compose.env"
    ports:
      - "5432:5432"
    volumes:
      - tunnelvision-db-data:/var/lib/postgresql/data

volumes:
  garage-data:
  garage-meta:
  tunnelvision-db-data:
