"""move image ordering to relation table

Revision ID: 19d49e00741c
Revises: 83e22d3a9cd1
Create Date: 2025-03-30 10:55:51.257448

"""
from alembic import op
import sqlalchemy as sa

from db import db, ImageAccessPointRelation, Image, Base, Mapped, mapped_column


# revision identifiers, used by Alembic.
revision = '19d49e00741c'
down_revision = '83e22d3a9cd1'
branch_labels = None
depends_on = None


# NOTE: This downgrade process will likely result in some data loss if there are items in the database that refer to the same image with different ordering.

class PriorImage(Image):
    ordering: Mapped[int] = mapped_column(use_existing_column=True)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('access_point_image_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordering', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('access_point_image_relation', schema=None) as batch_op:
        Base.metadata.bind = batch_op.get_bind()


        batch_op.execute(
            db.update(ImageAccessPointRelation)
                .where(Image.id == ImageAccessPointRelation.image_id)
                .values({ImageAccessPointRelation.ordering: PriorImage.ordering})
        )

        batch_op.alter_column('ordering',nullable=False)


    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('ordering')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordering', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('images', schema=None) as batch_op:
        Base.metadata.bind = batch_op.get_bind()


        batch_op.execute(
            db.update(Image)
                .where(Image.id == ImageAccessPointRelation.image_id)
                .values({PriorImage.ordering: ImageAccessPointRelation.ordering})
        )

        batch_op.alter_column('ordering',nullable=False)


    with op.batch_alter_table('access_point_image_relation', schema=None) as batch_op:
        batch_op.drop_column('ordering')

    # ### end Alembic commands ###
