"""Initial migration.

Revision ID: 1c4bb12413ae
Revises: 
Create Date: 2025-03-08 22:21:54.176841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4bb12413ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('alttext', sa.String(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('imghash', sa.String(), nullable=False),
    sa.Column('attribution', sa.String(), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.Column('fullsizehash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_point_image_relation',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'access_point_id')
    )
    op.create_table('access_point_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_point_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'access_point_id')
    )
    op.create_table('door_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter', sa.Enum('INTERIOR', 'EXTERIOR', 'VESTIBULE', name='sheltertype'), nullable=True),
    sa.Column('activation', sa.Enum('PUSH', 'WAVE', name='buttonactivation'), nullable=True),
    sa.Column('mount_surface', sa.Enum('WALL', 'POLE', name='mountsurface'), nullable=True),
    sa.Column('mount_style', sa.Enum('PROTRUDING', 'RECESSED', name='mountstyle'), nullable=True),
    sa.Column('powered_by', sa.Enum('HARDWIRED', 'BATTERY', name='powersource'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['access_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elevator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_min', sa.Integer(), nullable=False),
    sa.Column('floor_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['access_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('elevator')
    op.drop_table('door_button')
    op.drop_table('access_point_tags')
    op.drop_table('access_point_status')
    op.drop_table('access_point_image_relation')
    op.drop_table('access_point')
    op.drop_table('location')
    op.drop_table('tags')
    op.drop_table('images')
    op.drop_table('building')
    # ### end Alembic commands ###
