"""add concordances table

Revision ID: 40f4b882f16c
Revises: 729e70fdd84f
Create Date: 2026-01-25 12:41:31.063712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f4b882f16c'
down_revision = '729e70fdd84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_point_concordances',
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], ),
    sa.PrimaryKeyConstraint('access_point_id', 'identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('access_point_concordances')
    # ### end Alembic commands ###
