"""determine db structure for report storage

Revision ID: 56d6a9ebf681
Revises: 19d49e00741c
Create Date: 2025-04-12 17:29:41.219248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56d6a9ebf681'
down_revision = '19d49e00741c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_type', sa.Enum('UNKNOWN', 'BROKEN', 'IN_PROGRESS', 'FIXED', 'VERIFIED', name='statustype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_point_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'access_point_id')
    )
    op.drop_table('access_point_status')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordering', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('ordering')

    op.create_table('access_point_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_type', postgresql.ENUM('UNKNOWN', 'BROKEN', 'IN_PROGRESS', 'FIXED', 'VERIFIED', name='statustype'), autoincrement=False, nullable=False),
    sa.Column('ref', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_point.id'], name='access_point_status_access_point_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='access_point_status_pkey')
    )
    op.drop_table('access_point_reports')
    op.drop_table('report_status')
    op.drop_table('report')
    # ### end Alembic commands ###
