"""Optional image metadata.

Revision ID: 5ffc90638c96
Revises: 1c4bb12413ae
Create Date: 2025-03-12 20:20:24.126294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffc90638c96'
down_revision = '1c4bb12413ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('alttext',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('attribution',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('attribution',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('alttext',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
