"""add elevator manufacturer

Revision ID: 6d43d7fbd1b1
Revises: 40f4b882f16c
Create Date: 2026-01-25 13:08:40.578379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d43d7fbd1b1'
down_revision = '40f4b882f16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elevator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('elevator', schema=None) as batch_op:
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
