"""add unknown values to enums

Revision ID: 729e70fdd84f
Revises: c42357af00c2
Create Date: 2025-11-14 19:48:59.135466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729e70fdd84f'
down_revision = 'c42357af00c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sheltertype ADD VALUE 'UNKNOWN' before 'INTERIOR'")
    op.execute("ALTER TYPE buttonactivation ADD VALUE 'UNKNOWN' before 'PUSH'")
    op.execute("ALTER TYPE mountsurface ADD VALUE 'UNKNOWN' before 'WALL'")
    op.execute("ALTER TYPE mountstyle ADD VALUE 'UNKNOWN' before 'PROTRUDING'")
    op.execute("ALTER TYPE powersource ADD VALUE 'UNKNOWN' before 'HARDWIRED'")


    # with op.batch_alter_table('images', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('ordering', sa.Integer(), nullable=False))

    # ### end Alembic commands ###

# Removing values from an enum is not supported by postgres.
# downgrade not possible