"""add coordinate information

Revision ID: 74168007438d
Revises: 1eb3c5578ebd
Create Date: 2025-03-13 17:58:09.858326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74168007438d'
down_revision = '1eb3c5578ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
