"""new image paradigm

Revision ID: 83e22d3a9cd1
Revises: 4944530939b0
Create Date: 2025-03-30 09:56:13.239034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e22d3a9cd1'
down_revision = '4944530939b0'
branch_labels = None
depends_on = None

# NOTE: this is a one-way upgrade that will delete data. downgrade is not possible. PLEASE back up beforehand

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('fullsizehash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('imghash')
        batch_op.alter_column('naming_version',server_default='1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imghash', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('fullsizehash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('naming_version',server_default='0')

    # ### end Alembic commands ###
