"""finalize status type and ticket ref fields

Revision ID: b45c77d63c44
Revises: 74168007438d
Create Date: 2025-03-19 12:37:55.857649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45c77d63c44'
down_revision = '74168007438d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_point_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_type', sa.Enum('UNKNOWN', 'BROKEN', 'IN_PROGRESS', 'FIXED', 'VERIFIED', name='statustype'), nullable=False))
        batch_op.add_column(sa.Column('ref', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_point_status', schema=None) as batch_op:
        batch_op.drop_column('ref')
        batch_op.drop_column('status_type')

    # ### end Alembic commands ###
