"""finalize status type and ticket ref fields

Revision ID: b45c77d63c44
Revises: 74168007438d
Create Date: 2025-03-19 12:37:55.857649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b45c77d63c44'
down_revision = '74168007438d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # known bug https://github.com/sqlalchemy/alembic/issues/278

    statustype_enum = postgresql.ENUM('UNKNOWN', 'BROKEN', 'IN_PROGRESS', 'FIXED', 'VERIFIED', name='statustype', create_type=False)
    
    with op.batch_alter_table('access_point_status', schema=None) as batch_op:
        statustype_enum.create(batch_op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column('status_type', statustype_enum, nullable=False))
        batch_op.add_column(sa.Column('ref', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_point_status', schema=None) as batch_op:
        batch_op.drop_column('ref')
        batch_op.drop_column('status_type')

    # ### end Alembic commands ###
