"""add specific location notes to door buttons

Revision ID: ba0540bf9a6f
Revises: c42357af00c2
Create Date: 2025-11-12 21:36:06.100529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0540bf9a6f'
down_revision = 'c42357af00c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door_button', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_location_notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('door_button', schema=None) as batch_op:
        batch_op.drop_column('additional_location_notes')

    # ### end Alembic commands ###
