"""add thumbnail ref to access point table

Revision ID: e24dc296631c
Revises: e2ccb83d8717
Create Date: 2025-03-29 18:40:16.586343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24dc296631c'
down_revision = 'e2ccb83d8717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_ref', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'images', ['thumbnail_ref'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_point', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('thumbnail_ref')

    # ### end Alembic commands ###
