"""add door count to elevators

Revision ID: e2ccb83d8717
Revises: ab732a1a27a6
Create Date: 2025-03-25 10:16:36.952753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ccb83d8717'
down_revision = 'ab732a1a27a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elevator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('door_count', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elevator', schema=None) as batch_op:
        batch_op.drop_column('door_count')

    # ### end Alembic commands ###
